---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

ignore: |
  .git/
  node_modules/
  vendor/
  dashboard/node_modules/
  dashboard/.next/

rules:
  # Line length - allow longer lines for docker-compose and CI files
  line-length:
    max: 200
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Comments
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Key duplicates
  key-duplicates: enable

  # Truthy values
  truthy:
    level: warning
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  # Document start
  document-start: disable

  # Document end
  document-end: disable

  # Quoted strings
  quoted-strings: disable

  # Empty values
  empty-values: disable

  # Octal values
  octal-values: disable
